name: Deploy miller.style

on:
  push:
    paths:
      - "miller/**"
      - ".github/workflows/deploy-miller.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy miller
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./miller
          publish_branch: gh-pages
          cname: miller.style
